### PR TITLE
Select option

### PR DESCRIPTION
**Pull request by gpltaylor**
Fix issue [https://github.com/Lucifier129/react-lite/issues/125](#125)

There is a problem in IE/Edge where option.selected is not set based on the value within select.value. This means that Select boxes are not working correctly.

This pull request is spit into multiple parts to allow items to be cherry picked if required.

096c162 - The fix itself
c557114 - A dedicated test
e001d92 - Docs to explain what was changed and why
8227974 - Add an example to the test harness website
8583b50 - Files changed as part of the build process

Tested
This has been tested using browserstack.com for the latest version of browsers including mobile emulators (IOS 5,6,7 and Samsung Android)

* Edge
* IE 9, 10, 11
* Firefox
* Chrome
* Safari

Please let me know if there are any changes you would like me to make.

NOTE: We are using this patched version in a very large application with thousands of users with no reported issues.

### CODE REVIEW

**Comment by Lucifier129** [comment]
It seems like the checks had failded~

**Comment by gpltaylor** [comment]
Hello @Lucifier129, I will review this and get back to you. The HTML/innerHTML rendering has failed.

**Comment by gpltaylor** [comment]
Hello @Lucifier129 I have updated to fix the issue with dangerouslySetInnerHTML

**Comment by gpltaylor** [comment]
@Lucifier129 can you merge this before it goes stale. I would like to be running of the official npm.

**Comment by Lucifier129** [comment]
Hi @gpltaylor 

I had used [the same way](https://github.com/facebook/react/blob/15-stable/src/renderers/dom/client/wrappers/ReactDOMSelect.js#L88-L123) with regular react to fix this problem, and it can pass the test suit you provided above, so I must to close the pull-request.

**Pull request closed without merging**
